"""tips alert

Revision ID: 0bbe48c46baa
Revises: e24a89f7036d
Create Date: 2022-12-30 19:18:10.270866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbe48c46baa'
down_revision = 'e24a89f7036d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('tips_alerts', sa.Boolean(), nullable=False, server_default='t'))
    op.alter_column('preferences', 'tips_alerts', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'tips_alerts')
    # ### end Alembic commands ###
