"""clicks

Revision ID: 81ac810d1e28
Revises: d72243e4948b
Create Date: 2022-05-06 17:47:12.785892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ac810d1e28'
down_revision = 'd72243e4948b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participation', sa.Column('clicks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participation', 'clicks')
    # ### end Alembic commands ###
