"""baseline

Revision ID: 99523daf46ee
Revises: 7aa300c2911a
Create Date: 2022-05-02 21:11:45.493257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99523daf46ee'
down_revision = '7aa300c2911a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_supertokens', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('time_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id_supertokens'), 'users', ['id_supertokens'], unique=True)
    op.create_table('storage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('associationUserTeam',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('studies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public_studie_title', sa.String(), nullable=False),
    sa.Column('studie_description', sa.String(), nullable=False),
    sa.Column('audience_max', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_audience_max'), 'studies', ['audience_max'], unique=False)
    op.create_index(op.f('ix_studies_name'), 'studies', ['name'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('studie', 'typeform', 'welcome', 'farewell', 'extension', name='enumtasktype'), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('delete_cookie', sa.Boolean(), nullable=True),
    sa.Column('record_screen', sa.Boolean(), nullable=True),
    sa.Column('typeform_id', sa.String(), nullable=True),
    sa.Column('welcome_message', sa.String(), nullable=True),
    sa.Column('farewell_message', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('move', sa.Boolean(), nullable=True),
    sa.Column('edit', sa.Boolean(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('studie_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['studie_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_is_active'), 'task', ['is_active'], unique=False)
    op.create_index(op.f('ix_task_studie_id'), 'task', ['studie_id'], unique=False)
    op.create_index(op.f('ix_task_type'), 'task', ['type'], unique=False)
    op.create_table('participation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('participant_user', sa.String(), nullable=False),
    sa.Column('time_total', sa.Integer(), nullable=True),
    sa.Column('target_success', sa.Boolean(), nullable=True),
    sa.Column('video_storage_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['video_storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participation_is_active'), 'participation', ['is_active'], unique=False)
    op.create_index(op.f('ix_participation_participant_user'), 'participation', ['participant_user'], unique=False)
    op.create_index(op.f('ix_participation_task_id'), 'participation', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participation_task_id'), table_name='participation')
    op.drop_index(op.f('ix_participation_participant_user'), table_name='participation')
    op.drop_index(op.f('ix_participation_is_active'), table_name='participation')
    op.drop_table('participation')
    op.drop_index(op.f('ix_task_type'), table_name='task')
    op.drop_index(op.f('ix_task_studie_id'), table_name='task')
    op.drop_index(op.f('ix_task_is_active'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_studies_name'), table_name='studies')
    op.drop_index(op.f('ix_studies_audience_max'), table_name='studies')
    op.drop_table('studies')
    op.drop_table('associationUserTeam')
    op.drop_table('teams')
    op.drop_table('storage')
    op.drop_index(op.f('ix_users_id_supertokens'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
