"""Preferences and notifications

Revision ID: d72243e4948b
Revises: 99523daf46ee
Create Date: 2022-05-05 17:29:54.087329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72243e4948b'
down_revision = '99523daf46ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_alerts', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_seen'), 'notifications', ['seen'], unique=False)
    op.add_column('users', sa.Column('preferences_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'preferences', ['preferences_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'preferences_id')
    op.drop_index(op.f('ix_notifications_seen'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('preferences')
    # ### end Alembic commands ###
