"""Participation, user null true

Revision ID: dc4e32c435af
Revises: 4c37f7de847c
Create Date: 2022-05-11 19:37:14.159574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4e32c435af'
down_revision = '4c37f7de847c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participation', 'participant_user',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participation', 'participant_user',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
